import type { FantasyCardEffectType, FantasyCardRarity } from "./config";

export type FantasyCardDefinition = {
  id?: string;
  slug: string;
  name: string;
  icon: string;
  description: string;
  rarity: FantasyCardRarity;
  effectType: FantasyCardEffectType;
  effectConfig: Record<string, any>;
  enabled: boolean;
  requiresTarget: "NONE" | "SINGLE_PLAYER" | "DUO_PLAYERS" | "PREDICTION_TYPE";
  targetFilter?: "ANY_IN_LINEUP" | "ANY_IN_MARKET" | "BELOW_MEDIAN_PRICE" | "CHEAPEST_50_PERCENT";
};

export const FANTASY_CARDS_CATALOG: FantasyCardDefinition[] = [
  {
    slug: "super_captain",
    name: "Super Capitão",
    icon: "👑",
    description: "Seu capitão passa de 2x para 3x. O bônus adicional da carta é limitado a +8 pontos.",
    rarity: "LEGENDARY",
    effectType: "CAPTAIN_MULTIPLIER",
    effectConfig: { multiplier: 3, maxBonus: 8 },
    enabled: true,
    requiresTarget: "NONE",
  },
  {
    slug: "extra_credit",
    name: "Crédito Extra",
    icon: "💰",
    description: "+C$5,00 temporários para montar seu elenco nesta rodada sem alterar o patrimônio.",
    rarity: "COMMON",
    effectType: "BUDGET_BONUS",
    effectConfig: { bonus: 5 },
    enabled: true,
    requiresTarget: "NONE",
  },
  {
    slug: "double_prediction",
    name: "Palpite Duplo",
    icon: "🎯",
    description: "Escolha 2 jogadores do mercado: um para marcar 2 gols e outro para dar 2 assistências. Se os dois conseguirem, ganhe +6 pontos.",
    rarity: "RARE",
    effectType: "PREDICTION_MULTIPLIER",
    effectConfig: { bonus: 6 },
    enabled: true,
    requiresTarget: "DUO_PLAYERS",
  },
  {
    slug: "bargain",
    name: "Barganha",
    icon: "🤑",
    description: "Antes de montar a escalação, escolha 1 atleta do mercado: ele terá 20% de desconto no orçamento desta rodada.",
    rarity: "COMMON",
    effectType: "PLAYER_DISCOUNT",
    effectConfig: { discountPercent: 20 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_MARKET",
  },
  {
    slug: "vice_captain",
    name: "Vice-Capitão",
    icon: "🛡️",
    description: "Você escolhe o Vice-Capitão. Se ele superar o Capitão em pontos-base, a braçadeira e o multiplicador 2x passam para o Vice. Bônus líquido limitado a +8 pontos.",
    rarity: "EPIC",
    effectType: "VICE_CAPTAIN",
    effectConfig: { maxBonus: 8 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "golden_goal",
    name: "Gol de Ouro",
    icon: "⚽",
    description: "Se o jogador selecionado marcar 1 ou mais gols, ganhe +3 pontos extras.",
    rarity: "COMMON",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { metric: "goals", threshold: 1, bonus: 3 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "golden_assist",
    name: "Passe de Ouro",
    icon: "🍽️",
    description: "Se o jogador selecionado der 1 ou mais assistências, ganhe +3 pontos extras.",
    rarity: "COMMON",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { metric: "assists", threshold: 1, bonus: 3 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "scout",
    name: "Caça-Talentos",
    icon: "💎",
    description: "Ganhe 50% dos pontos base (máx +6 pts) de um atleta escalado abaixo da mediana de preço.",
    rarity: "EPIC",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { percentage: 0.5, maxBonus: 6, belowMedianPrice: true },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "BELOW_MEDIAN_PRICE",
  },
  {
    slug: "duo",
    name: "Dobradinha",
    icon: "⚡",
    description: "Escolha 2 jogadores da sua escalação. Se ambos ficarem acima da média da rodada, ganhe +5 pontos.",
    rarity: "RARE",
    effectType: "CONDITIONAL_DUO_BONUS",
    effectConfig: { bonus: 5, aboveRoundAverage: true },
    enabled: true,
    requiresTarget: "DUO_PLAYERS",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "all_in",
    name: "All-In",
    icon: "🎰",
    description: "Escolha qualquer atleta do mercado. Se ele terminar no TOP 5 da rodada, ganhe +6 pontos.",
    rarity: "EPIC",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { bonus: 6, topRank: 5 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_MARKET",
  },
  {
    slug: "so_vim_pela_resenha",
    name: "Só Vim Pela Resenha",
    icon: "🪑",
    description: "Se o jogador terminar com 0 gols, 0 assistências e 2 ou mais vitórias, ganhe +3 pontos.",
    rarity: "COMMON",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { maxGoals: 0, maxAssists: 0, minWins: 2, bonus: 3 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "samu_do_cartola",
    name: "Samu do Cartola",
    icon: "🩺",
    description: "Se o jogador escolhido terminar com pontuação negativa, a pontuação dele é ajustada para 0.",
    rarity: "COMMON",
    effectType: "PLAYER_SCORE_PROTECTION",
    effectConfig: { mode: "NEGATIVE_TO_ZERO" },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "tava_em_campo",
    name: "Tava em Campo?",
    icon: "👻",
    description: "Se o escolhido for o menor pontuador-base da sua escalação, ganhe +2 pontos.",
    rarity: "COMMON",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { lineupRank: "LOWEST", bonus: 2 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "my_mvp",
    name: "Craque do Meu Time",
    icon: "🌟",
    description: "Se o escolhido for o maior pontuador-base da sua escalação, ganhe +4 pontos. Empate no topo conta.",
    rarity: "RARE",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { lineupRank: "HIGHEST", bonus: 4 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "head_to_head",
    name: "Duelo Direto",
    icon: "⚔️",
    description: "Escolha um escalado. O BQ sorteia um adversário confirmado; se o seu jogador fizer mais pontos-base, ganhe +5 pontos.",
    rarity: "RARE",
    effectType: "HEAD_TO_HEAD_BONUS",
    effectConfig: { bonus: 5 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "bagre_insurance",
    name: "Seguro contra Bagres",
    icon: "🛟",
    description: "Se o escolhido ficar negativo, vira 0. Se ficar positivo abaixo da mediana da rodada, ganhe +2 pontos.",
    rarity: "RARE",
    effectType: "PLAYER_SCORE_PROTECTION",
    effectConfig: { mode: "NEGATIVE_OR_BELOW_MEDIAN", belowMedianBonus: 2 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "bagre_value_shield",
    name: "Fundo Garantidor de Bagres",
    icon: "💎",
    description: "Se o jogador escolhido desvalorizar, recupere a perda de patrimônio em até C$2,00.",
    rarity: "RARE",
    effectType: "PLAYER_VALUE_SHIELD",
    effectConfig: { maxRecovery: 2 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "triple_crown",
    name: "Tríplice Coroa",
    icon: "🏆",
    description: "Se o escolhido fizer 1+ gol, 1+ assistência e 1+ vitória, ganhe +6 pontos.",
    rarity: "EPIC",
    effectType: "CONDITIONAL_PLAYER_BONUS",
    effectConfig: { minGoals: 1, minAssists: 1, minWins: 1, bonus: 6 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "bagre_or_craque",
    name: "Bagre ou Craque?",
    icon: "🎭",
    description: "Se o escolhido ficar negativo, vira 0. Se terminar no TOP 5 da rodada, ganhe +5 pontos.",
    rarity: "EPIC",
    effectType: "PLAYER_SCORE_PROTECTION",
    effectConfig: { mode: "NEGATIVE_OR_TOP_RANK", topRank: 5, topBonus: 5 },
    enabled: true,
    requiresTarget: "SINGLE_PLAYER",
    targetFilter: "ANY_IN_LINEUP",
  },
  {
    slug: "dream_team",
    name: "Seleção dos Sonhos",
    icon: "👑",
    description: "Se os 5 jogadores da sua escalação terminarem no TOP 8 de pontuação-base, ganhe +8 pontos.",
    rarity: "LEGENDARY",
    effectType: "LINEUP_CONDITION_BONUS",
    effectConfig: { allPlayersTopRank: 8, bonus: 8 },
    enabled: true,
    requiresTarget: "NONE",
  },
  {
    slug: "safe_prediction",
    name: "Palpite Seguro",
    icon: "🔮",
    description: "Escolha 2 jogadores no Desafio da Rodada. Se qualquer um cumprir, ganhe 60% da recompensa.",
    rarity: "RARE",
    effectType: "SAFE_PREDICTION",
    effectConfig: { rewardMultiplier: 0.6 },
    enabled: false,
    requiresTarget: "NONE",
  },
  {
    slug: "emergency_sub",
    name: "Reserva de Emergência",
    icon: "🔄",
    description: "Um 6º jogador entra no lugar de um titular do seu time que pontuou negativo na rodada.",
    rarity: "EPIC",
    effectType: "EMERGENCY_SUB",
    effectConfig: {},
    enabled: false,
    requiresTarget: "SINGLE_PLAYER",
  },
];

export function getCardBySlug(slug: string): FantasyCardDefinition | undefined {
  return FANTASY_CARDS_CATALOG.find((card) => card.slug === slug);
}
