import Link from "next/link";
import { notFound } from "next/navigation";
import { PlayerAvatar } from "@/components/PlayerAvatar";
import { getFantasyUserRoundHistory } from "@/lib/actions/fantasy";

export default async function FantasyUserRoundHistoryPage({ params }: { params: Promise<{ userId: string; roundId: string }> }) {
  const { userId, roundId } = await params;
  const data = await getFantasyUserRoundHistory(userId, roundId);
  if (!data) notFound();
  const name = (data.history.player as any)?.name || "Cartoleiro";
  return <div className="space-y-5"><header><Link href={`/cartola/ranking/${userId}`} className="text-xs font-bold text-accent">← Histórico de {name}</Link><h1 className="mt-3 text-xl font-black text-foreground">Rodada {String(data.round?.number || 0).padStart(2, "0")}</h1><p className="mt-1 text-xs text-muted">{data.round?.date} · total {Number(data.lineup.total_points || 0).toFixed(1)} pts</p></header><section className="space-y-2"><h2 className="text-xs font-black uppercase text-muted">Escalação</h2>{(data.lineup.fantasy_lineup_players || []).map((item: any) => { const playerName = item.player_name_locked || item.players?.name || "Jogador"; const isCaptain = item.player_id === data.lineup.captain_player_id; return <Link key={item.id} href={`/cartola/ranking/${userId}/${roundId}/${item.player_id}`} className="glass-card flex items-center gap-3 p-3 transition-colors hover:bg-surface-hover"><PlayerAvatar name={playerName} avatarUrl={item.avatar_url_locked || item.players?.avatar_url} className="h-10 w-10 rounded-full bg-surface text-xs font-black text-accent" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-foreground">{playerName}{isCaptain ? " · Capitão" : ""}</p><p className="text-[10px] text-muted">Base {Number(item.base_points || 0).toFixed(1)} · bônus {Number(item.captain_bonus || 0).toFixed(1)} · toque para detalhar</p></div><strong className="text-base text-accent">{Number(item.total_points || 0).toFixed(1)}</strong></Link>; })}</section><section className="grid grid-cols-2 gap-2"><div className="glass-card p-3"><p className="text-[9px] font-black uppercase text-muted">Palpite artilheiro</p><p className="mt-1 text-xs font-bold text-foreground">{data.lineup.top_scorer_player_id ? "Registrado" : "Não enviado"}</p></div><div className="glass-card p-3"><p className="text-[9px] font-black uppercase text-muted">Palpite garçom</p><p className="mt-1 text-xs font-bold text-foreground">{data.lineup.top_assist_player_id ? "Registrado" : "Não enviado"}</p></div></section></div>;
}
