"use client";

import { useTransition } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, X } from "@/components/icons";
import { claimPassCosmetic, type CosmeticPassReward } from "@/lib/actions/cosmetics";
import { cosmeticImage, cosmeticVisual, COSMETIC_SLOT_LABELS, rarityClass } from "@/lib/fantasy/cosmetics";

export function PassRewardModal({ reward, progress, onClose }: { reward: CosmeticPassReward | null; progress: number; onClose: () => void }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  if (!reward) return null;
  const unlocked = progress >= reward.house;
  const secret = reward.house === 40 && !unlocked;
  const selected = reward.selectedCosmeticId;
  return <div className="fixed inset-0 z-[100] flex items-end bg-black/70 p-3 backdrop-blur-sm sm:items-center sm:justify-center" role="dialog" aria-modal="true" aria-label="Recompensa do Passe" onClick={onClose}>
    <section className="w-full max-w-md overflow-hidden rounded-3xl border border-accent/35 bg-[#07150d] shadow-2xl" onClick={(event) => event.stopPropagation()}>
      <header className="flex items-start justify-between border-b border-white/10 p-4"><div><p className="font-athletic text-[10px] font-black uppercase tracking-[.16em] text-accent">Casa {reward.house} · Passe BQ</p><h2 className="mt-1 text-lg font-black text-white">{secret ? "Recompensa secreta" : reward.rewardType === "card_pack" ? `Pacote ${reward.cardTier === "gold" ? "Ouro" : "Bronze"}` : selected ? "Escolha concluída" : unlocked ? "Escolha sua recompensa" : "Recompensa bloqueada"}</h2></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-muted hover:bg-white/10 hover:text-white" aria-label="Fechar"><X className="h-5 w-5" /></button></header>
      {secret ? <div className="p-6 text-center"><span className="text-4xl">🔒</span><p className="mt-3 text-sm font-black text-white">A casa 40 guarda o prêmio final.</p><p className="mt-2 text-xs leading-5 text-muted">Continue jogando para revelar a escolha lendária.</p></div> : reward.rewardType === "card_pack" ? <div className="p-6 text-center"><span className="text-4xl">🎴</span><p className="mt-3 text-sm font-black text-white">{unlocked ? "Seu pacote já está no Cartola." : "Avance até esta casa para receber o pacote."}</p><p className="mt-2 text-xs leading-5 text-muted">Pacotes são entregues automaticamente e podem ser abertos pelo Cartola.</p>{unlocked && <button type="button" onClick={() => router.push("/cartola")} className="mt-5 rounded-xl bg-accent px-4 py-3 text-xs font-black uppercase text-background">Abrir Cartola</button>}</div> : <div className="p-4"><p className="mb-3 text-xs leading-5 text-muted">{unlocked ? selected ? "Esta escolha é permanente; você pode equipar ou desequipar o item quando quiser." : "Escolha um dos dois itens. A decisão é permanente, mas o equipamento fica livre." : "Os itens ficam visíveis, mas só serão resgatados quando você alcançar esta casa. Jogue, escale e faça gols ou assistências para avançar."}</p><div className="grid grid-cols-2 gap-3">{reward.options.map((item) => { const image = cosmeticImage(item.assetKey); const chosen = selected === item.id; return <article key={item.id} className={`overflow-hidden rounded-2xl border bg-surface ${rarityClass(item.rarity)} ${chosen ? "ring-2 ring-accent" : ""}`}><div className={`h-20 bg-gradient-to-br ${cosmeticVisual(item.assetKey)}`} style={image ? { backgroundImage: `linear-gradient(rgba(3,14,8,.12),rgba(3,14,8,.62)),url(${image})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined} /><div className="p-3"><p className="text-[8px] font-black uppercase text-muted">{COSMETIC_SLOT_LABELS[item.slot]}</p><h3 className="mt-1 text-xs font-black text-white">{item.name}</h3><p className="mt-1 min-h-8 text-[10px] leading-4 text-muted">{item.description}</p>{chosen ? <span className="mt-3 block rounded-xl bg-accent px-2 py-2 text-center text-[9px] font-black uppercase text-background">Escolhido</span> : <button type="button" disabled={!unlocked || Boolean(selected) || pending} onClick={() => startTransition(async () => { const result = await claimPassCosmetic(reward.id, item.id); if (result.success) { router.refresh(); onClose(); } else window.alert(result.error || "Não foi possível resgatar."); })} className="mt-3 w-full rounded-xl border border-accent/35 bg-accent/10 px-2 py-2 text-[9px] font-black uppercase text-accent disabled:opacity-40">{unlocked ? "Escolher" : "Bloqueado"}</button>}</div></article>; })}</div><div className="mt-4 flex items-center gap-2 rounded-xl border border-accent/15 bg-accent/5 p-2.5 text-[10px] text-muted"><Sparkles className="h-4 w-4 shrink-0 text-accent" />Nenhum item do Passe muda pontos, Cartoletas ou ranking.</div></div>}
    </section>
  </div>;
}
