-- Auditoria imutavel das marcacoes de pagamento do Transfermarket.

CREATE TABLE IF NOT EXISTS round_payment_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  round_id UUID NOT NULL REFERENCES rounds(id) ON DELETE CASCADE,
  target_player_id UUID REFERENCES players(id) ON DELETE SET NULL,
  target_player_name TEXT NOT NULL,
  paid BOOLEAN NOT NULL,
  changed_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  changed_by_player_id UUID REFERENCES players(id) ON DELETE SET NULL,
  changed_by_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS round_payment_audit_round_order_idx
ON round_payment_audit (round_id, id);

CREATE INDEX IF NOT EXISTS round_payment_audit_created_at_idx
ON round_payment_audit (created_at DESC);

CREATE OR REPLACE FUNCTION record_round_payment_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor_user_id UUID;
  actor_player_id UUID;
  actor_name TEXT;
  target_name TEXT;
BEGIN
  -- A criacao automatica da caixa desmarcada nao representa uma acao humana.
  IF TG_OP = 'INSERT' AND NEW.paid = false THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.paid IS NOT DISTINCT FROM OLD.paid THEN
    RETURN NEW;
  END IF;

  actor_user_id := auth.uid();

  SELECT account.player_id, player.name
  INTO actor_player_id, actor_name
  FROM account_profiles AS account
  LEFT JOIN players AS player ON player.id = account.player_id
  WHERE account.user_id = actor_user_id;

  IF actor_name IS NULL THEN
    SELECT COALESCE(NULLIF(split_part(auth_user.email, '@', 1), ''), 'Conta removida')
    INTO actor_name
    FROM auth.users AS auth_user
    WHERE auth_user.id = actor_user_id;
  END IF;

  SELECT name INTO target_name
  FROM players
  WHERE id = NEW.player_id;

  INSERT INTO round_payment_audit (
    round_id,
    target_player_id,
    target_player_name,
    paid,
    changed_by_user_id,
    changed_by_player_id,
    changed_by_name
  )
  VALUES (
    NEW.round_id,
    NEW.player_id,
    COALESCE(target_name, 'Jogador removido'),
    NEW.paid,
    actor_user_id,
    actor_player_id,
    COALESCE(actor_name, 'Conta nao identificada')
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS round_payments_record_audit ON round_payments;
CREATE TRIGGER round_payments_record_audit
AFTER INSERT OR UPDATE OF paid ON round_payments
FOR EACH ROW
EXECUTE FUNCTION record_round_payment_audit();

ALTER TABLE round_payment_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read payment audit" ON round_payment_audit;
CREATE POLICY "Admins can read payment audit"
ON round_payment_audit FOR SELECT
TO authenticated
USING (is_app_admin());

REVOKE ALL ON round_payment_audit FROM anon, authenticated;
GRANT SELECT ON round_payment_audit TO authenticated;

REVOKE ALL ON FUNCTION record_round_payment_audit() FROM PUBLIC, anon, authenticated;
