-- Historico do elenco, leitura individual dos ADMs e uniao segura de perfis.

ALTER TABLE players
ADD COLUMN IF NOT EXISTS registration_source TEXT NOT NULL DEFAULT 'admin';

ALTER TABLE players
DROP CONSTRAINT IF EXISTS players_registration_source_check;

ALTER TABLE players
ADD CONSTRAINT players_registration_source_check
CHECK (registration_source IN ('legacy', 'site_signup', 'admin'));

ALTER TABLE players
ADD COLUMN IF NOT EXISTS created_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;

UPDATE players
SET registration_source = 'legacy'
WHERE registration_source = 'admin'
  AND created_at < now() - interval '1 minute';

CREATE TABLE IF NOT EXISTS player_registration_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id UUID REFERENCES players(id) ON DELETE SET NULL,
  player_name TEXT NOT NULL,
  avatar_url TEXT,
  member_category TEXT NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('legacy', 'site_signup', 'admin')),
  created_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS player_registration_events_created_idx
ON player_registration_events (created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS admin_roster_reads (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO player_registration_events (
  player_id, player_name, avatar_url, member_category, source, created_by_user_id, created_at
)
SELECT player.id, player.name, player.avatar_url, player.member_category, 'legacy', NULL, player.created_at
FROM players AS player
WHERE NOT EXISTS (
  SELECT 1 FROM player_registration_events AS event WHERE event.player_id = player.id
);

INSERT INTO admin_roster_reads (user_id, last_seen_at)
SELECT user_id, now()
FROM account_profiles
WHERE role = 'admin'
ON CONFLICT (user_id) DO NOTHING;

CREATE OR REPLACE FUNCTION record_player_registration()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO player_registration_events (
    player_id, player_name, avatar_url, member_category, source, created_by_user_id, created_at
  ) VALUES (
    NEW.id, NEW.name, NEW.avatar_url, NEW.member_category,
    NEW.registration_source, NEW.created_by_user_id, NEW.created_at
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS players_record_registration ON players;
CREATE TRIGGER players_record_registration
AFTER INSERT ON players
FOR EACH ROW EXECUTE FUNCTION record_player_registration();

-- Mantem o comportamento atual do cadastro e identifica a origem do perfil.
CREATE OR REPLACE FUNCTION create_player_account()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  created_player_id UUID;
  requested_profile TEXT;
  requested_goalkeeper BOOLEAN;
  player_name TEXT;
BEGIN
  IF EXISTS (SELECT 1 FROM account_profiles WHERE user_id = NEW.id) THEN
    RETURN NEW;
  END IF;

  requested_profile := COALESCE(NEW.raw_user_meta_data ->> 'player_profile', 'midfield');
  IF requested_profile NOT IN ('offensive', 'midfield', 'defensive') THEN
    requested_profile := 'midfield';
  END IF;

  requested_goalkeeper := lower(COALESCE(NEW.raw_user_meta_data ->> 'is_goalkeeper', 'false'))
    IN ('true', '1', 'yes', 'on');

  player_name := COALESCE(
    NULLIF(TRIM(NEW.raw_user_meta_data ->> 'name'), ''),
    NULLIF(TRIM(NEW.raw_user_meta_data ->> 'full_name'), ''),
    NULLIF(TRIM(NEW.raw_user_meta_data ->> 'display_name'), '')
  );
  IF player_name IS NULL THEN
    player_name := SPLIT_PART(COALESCE(NEW.email, 'Jogador'), '@', 1);
  END IF;

  INSERT INTO players (
    name, nickname, player_profile, is_goalkeeper, avatar_url,
    registration_source, created_by_user_id
  ) VALUES (
    LEFT(player_name, 120),
    NULLIF(LEFT(TRIM(NEW.raw_user_meta_data ->> 'nickname'), 60), ''),
    requested_profile,
    requested_goalkeeper,
    NULL,
    'site_signup',
    NEW.id
  )
  RETURNING id INTO created_player_id;

  INSERT INTO account_profiles (user_id, role, player_id)
  VALUES (NEW.id, 'player', created_player_id);

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION initialize_admin_roster_read()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.role = 'admin' AND TG_OP = 'INSERT' THEN
    INSERT INTO admin_roster_reads (user_id, last_seen_at)
    VALUES (NEW.user_id, now())
    ON CONFLICT (user_id) DO UPDATE SET last_seen_at = EXCLUDED.last_seen_at;
  ELSIF NEW.role = 'admin' AND OLD.role IS DISTINCT FROM 'admin' THEN
    INSERT INTO admin_roster_reads (user_id, last_seen_at)
    VALUES (NEW.user_id, now())
    ON CONFLICT (user_id) DO UPDATE SET last_seen_at = EXCLUDED.last_seen_at;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS account_profiles_initialize_roster_read ON account_profiles;
CREATE TRIGGER account_profiles_initialize_roster_read
AFTER INSERT OR UPDATE OF role ON account_profiles
FOR EACH ROW EXECUTE FUNCTION initialize_admin_roster_read();

CREATE OR REPLACE FUNCTION mark_roster_activity_seen()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT is_app_admin() THEN
    RAISE EXCEPTION 'Somente administradores podem atualizar esta leitura.';
  END IF;
  INSERT INTO admin_roster_reads (user_id, last_seen_at)
  VALUES (auth.uid(), now())
  ON CONFLICT (user_id) DO UPDATE SET last_seen_at = EXCLUDED.last_seen_at;
END;
$$;

-- O convidado e o registro sobrevivente; o perfil automatico e consolidado e removido.
CREATE OR REPLACE FUNCTION merge_player_profiles(p_guest_id UUID, p_registered_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  guest players%ROWTYPE;
  registered players%ROWTYPE;
  registered_user_id UUID;
BEGIN
  IF NOT is_app_admin() THEN
    RAISE EXCEPTION 'Somente administradores podem unir perfis.';
  END IF;
  IF p_guest_id = p_registered_id THEN
    RAISE EXCEPTION 'Escolha dois perfis diferentes.';
  END IF;

  SELECT * INTO guest FROM players WHERE id = p_guest_id FOR UPDATE;
  SELECT * INTO registered FROM players WHERE id = p_registered_id FOR UPDATE;
  IF guest.id IS NULL OR registered.id IS NULL THEN
    RAISE EXCEPTION 'Um dos perfis nao foi encontrado.';
  END IF;
  IF guest.member_category <> 'guest' THEN
    RAISE EXCEPTION 'O perfil sobrevivente precisa ser um convidado.';
  END IF;
  IF registered.member_category <> 'player' THEN
    RAISE EXCEPTION 'A conta cadastrada precisa estar vinculada a um jogador oficial.';
  END IF;
  IF EXISTS (SELECT 1 FROM account_profiles WHERE player_id = p_guest_id) THEN
    RAISE EXCEPTION 'O convidado ja esta vinculado a uma conta.';
  END IF;
  SELECT user_id INTO registered_user_id FROM account_profiles WHERE player_id = p_registered_id;
  IF registered_user_id IS NULL THEN
    RAISE EXCEPTION 'O jogador oficial escolhido nao possui uma conta vinculada.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM match_players
    WHERE player_id IN (p_guest_id, p_registered_id) AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Nao e possivel unir perfis durante uma partida ativa.';
  END IF;

  INSERT INTO league_members (league_id, player_id, role, is_active, joined_at)
  SELECT league_id, p_guest_id, role, is_active, joined_at
  FROM league_members WHERE player_id = p_registered_id
  ON CONFLICT (league_id, player_id) DO UPDATE SET
    role = CASE WHEN league_members.role = 'admin' OR EXCLUDED.role = 'admin' THEN 'admin' ELSE 'player' END,
    is_active = league_members.is_active OR EXCLUDED.is_active,
    joined_at = LEAST(league_members.joined_at, EXCLUDED.joined_at);
  DELETE FROM league_members WHERE player_id = p_registered_id;

  INSERT INTO round_players (round_id, player_id, availability_status, availability_updated_at)
  SELECT round_id, p_guest_id, availability_status, availability_updated_at
  FROM round_players WHERE player_id = p_registered_id
  ON CONFLICT (round_id, player_id) DO UPDATE SET
    availability_status = CASE WHEN round_players.availability_status = 'injured' OR EXCLUDED.availability_status = 'injured' THEN 'injured' ELSE 'available' END,
    availability_updated_at = GREATEST(round_players.availability_updated_at, EXCLUDED.availability_updated_at);

  INSERT INTO round_payments (round_id, player_id, paid, paid_at, created_at)
  SELECT round_id, p_guest_id, paid, paid_at, created_at
  FROM round_payments WHERE player_id = p_registered_id
  ON CONFLICT (round_id, player_id) DO UPDATE SET
    paid = round_payments.paid OR EXCLUDED.paid,
    paid_at = CASE
      WHEN round_payments.paid_at IS NULL THEN EXCLUDED.paid_at
      WHEN EXCLUDED.paid_at IS NULL THEN round_payments.paid_at
      ELSE LEAST(round_payments.paid_at, EXCLUDED.paid_at)
    END;

  INSERT INTO team_players (team_id, player_id)
  SELECT team_id, p_guest_id FROM team_players WHERE player_id = p_registered_id
  ON CONFLICT (team_id, player_id) DO NOTHING;
  DELETE FROM team_players WHERE player_id = p_registered_id;

  UPDATE match_events SET player_id = p_guest_id WHERE player_id = p_registered_id;
  UPDATE match_events SET assist_player_id = p_guest_id WHERE assist_player_id = p_registered_id;

  INSERT INTO player_round_stats (
    player_id, round_id, league_id, games, goals, assists, wins, draws, losses, points
  )
  SELECT p_guest_id, round_id, league_id, games, goals, assists, wins, draws, losses, points
  FROM player_round_stats WHERE player_id = p_registered_id
  ON CONFLICT (player_id, round_id) DO UPDATE SET
    games = player_round_stats.games + EXCLUDED.games,
    goals = player_round_stats.goals + EXCLUDED.goals,
    assists = player_round_stats.assists + EXCLUDED.assists,
    wins = player_round_stats.wins + EXCLUDED.wins,
    draws = player_round_stats.draws + EXCLUDED.draws,
    losses = player_round_stats.losses + EXCLUDED.losses,
    points = player_round_stats.points + EXCLUDED.points;
  DELETE FROM player_round_stats WHERE player_id = p_registered_id;

  INSERT INTO player_round_fitness (
    player_id, round_id, distance_km, average_speed_kmh, created_at, updated_at
  )
  SELECT p_guest_id, round_id, distance_km, average_speed_kmh, created_at, updated_at
  FROM player_round_fitness WHERE player_id = p_registered_id
  ON CONFLICT (player_id, round_id) DO UPDATE SET
    distance_km = CASE WHEN EXCLUDED.updated_at >= player_round_fitness.updated_at THEN EXCLUDED.distance_km ELSE player_round_fitness.distance_km END,
    average_speed_kmh = CASE WHEN EXCLUDED.updated_at >= player_round_fitness.updated_at THEN EXCLUDED.average_speed_kmh ELSE player_round_fitness.average_speed_kmh END,
    updated_at = GREATEST(player_round_fitness.updated_at, EXCLUDED.updated_at);
  DELETE FROM player_round_fitness WHERE player_id = p_registered_id;

  DELETE FROM callup_entries AS source
  WHERE source.player_id = p_registered_id
    AND EXISTS (
      SELECT 1 FROM callup_entries AS target
      WHERE target.callup_id = source.callup_id AND target.player_id = p_guest_id
    );
  UPDATE callup_entries SET player_id = p_guest_id WHERE player_id = p_registered_id;

  DELETE FROM match_players AS source
  WHERE source.player_id = p_registered_id
    AND EXISTS (
      SELECT 1 FROM match_players AS target
      WHERE target.match_id = source.match_id AND target.player_id = p_guest_id
    );
  UPDATE match_players SET player_id = p_guest_id WHERE player_id = p_registered_id;

  UPDATE match_substitutions SET player_out_id = p_guest_id WHERE player_out_id = p_registered_id;
  UPDATE match_substitutions SET player_in_id = p_guest_id WHERE player_in_id = p_registered_id;
  UPDATE rounds SET best_goalkeeper_player_id = p_guest_id WHERE best_goalkeeper_player_id = p_registered_id;
  UPDATE round_payment_audit SET target_player_id = p_guest_id WHERE target_player_id = p_registered_id;
  UPDATE round_payment_audit SET changed_by_player_id = p_guest_id WHERE changed_by_player_id = p_registered_id;

  UPDATE account_profiles
  SET player_id = p_guest_id, updated_at = now()
  WHERE user_id = registered_user_id;

  DELETE FROM round_players WHERE player_id = p_registered_id;
  DELETE FROM round_payments WHERE player_id = p_registered_id;

  UPDATE players SET
    name = registered.name,
    nickname = COALESCE(registered.nickname, guest.nickname),
    avatar_url = COALESCE(registered.avatar_url, guest.avatar_url),
    player_profile = COALESCE(registered.player_profile, guest.player_profile, 'midfield'),
    is_goalkeeper = registered.is_goalkeeper OR guest.is_goalkeeper,
    member_category = 'player',
    is_selectable = true,
    profile_bio = COALESCE(registered.profile_bio, guest.profile_bio),
    show_fitness_stats = registered.show_fitness_stats OR guest.show_fitness_stats
  WHERE id = p_guest_id;

  DELETE FROM players WHERE id = p_registered_id;
  RETURN p_guest_id;
END;
$$;

ALTER TABLE player_registration_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_roster_reads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins read registration history" ON player_registration_events;
CREATE POLICY "Admins read registration history"
ON player_registration_events FOR SELECT TO authenticated
USING (is_app_admin());

DROP POLICY IF EXISTS "Admins read own roster state" ON admin_roster_reads;
CREATE POLICY "Admins read own roster state"
ON admin_roster_reads FOR SELECT TO authenticated
USING (is_app_admin() AND user_id = auth.uid());

DROP POLICY IF EXISTS "Admins insert own roster state" ON admin_roster_reads;
CREATE POLICY "Admins insert own roster state"
ON admin_roster_reads FOR INSERT TO authenticated
WITH CHECK (is_app_admin() AND user_id = auth.uid());

DROP POLICY IF EXISTS "Admins update own roster state" ON admin_roster_reads;
CREATE POLICY "Admins update own roster state"
ON admin_roster_reads FOR UPDATE TO authenticated
USING (is_app_admin() AND user_id = auth.uid())
WITH CHECK (is_app_admin() AND user_id = auth.uid());

REVOKE ALL ON player_registration_events, admin_roster_reads FROM anon, authenticated;
GRANT SELECT ON player_registration_events TO authenticated;
GRANT SELECT, INSERT, UPDATE ON admin_roster_reads TO authenticated;
GRANT EXECUTE ON FUNCTION mark_roster_activity_seen() TO authenticated;
GRANT EXECUTE ON FUNCTION merge_player_profiles(UUID, UUID) TO authenticated;

REVOKE ALL ON FUNCTION record_player_registration() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION initialize_admin_roster_read() FROM PUBLIC, anon, authenticated;
