-- Gestão segura de administradores pelo próprio aplicativo.

CREATE TABLE IF NOT EXISTS public.admin_role_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  previous_role TEXT NOT NULL CHECK (previous_role IN ('admin', 'player')),
  new_role TEXT NOT NULL CHECK (new_role IN ('admin', 'player')),
  changed_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_role_audit_created_idx
ON public.admin_role_audit (created_at DESC, id DESC);

ALTER TABLE public.admin_role_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_role_audit_admin_read ON public.admin_role_audit;
CREATE POLICY admin_role_audit_admin_read
ON public.admin_role_audit FOR SELECT
TO authenticated
USING (public.is_app_admin());

REVOKE ALL ON public.admin_role_audit FROM PUBLIC, anon;
REVOKE INSERT, UPDATE, DELETE ON public.admin_role_audit FROM authenticated;
GRANT SELECT ON public.admin_role_audit TO authenticated;

CREATE OR REPLACE FUNCTION public.manage_account_admin_role(
  p_target_user_id UUID,
  p_make_admin BOOLEAN
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_role TEXT;
  desired_role TEXT := CASE WHEN p_make_admin THEN 'admin' ELSE 'player' END;
  admin_count INTEGER;
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_app_admin() THEN
    RAISE EXCEPTION 'Somente administradores podem alterar acessos.';
  END IF;

  SELECT role INTO current_role
  FROM public.account_profiles
  WHERE user_id = p_target_user_id
  FOR UPDATE;

  IF current_role IS NULL THEN
    RAISE EXCEPTION 'Conta cadastrada nao encontrada.';
  END IF;

  IF current_role = desired_role THEN
    RETURN desired_role;
  END IF;

  IF NOT p_make_admin THEN
    IF p_target_user_id = auth.uid() THEN
      RAISE EXCEPTION 'Voce nao pode remover o proprio acesso de administrador.';
    END IF;

    SELECT count(*)::INTEGER INTO admin_count
    FROM public.account_profiles
    WHERE role = 'admin';

    IF admin_count <= 1 THEN
      RAISE EXCEPTION 'O aplicativo precisa manter pelo menos um administrador.';
    END IF;
  END IF;

  UPDATE public.account_profiles
  SET role = desired_role, updated_at = now()
  WHERE user_id = p_target_user_id;

  INSERT INTO public.admin_role_audit (
    target_user_id,
    previous_role,
    new_role,
    changed_by_user_id
  ) VALUES (
    p_target_user_id,
    current_role,
    desired_role,
    auth.uid()
  );

  RETURN desired_role;
END;
$$;

REVOKE ALL ON FUNCTION public.manage_account_admin_role(UUID, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.manage_account_admin_role(UUID, BOOLEAN) TO authenticated;

-- Impede alterações diretas que contornem as validações e a auditoria acima.
DROP POLICY IF EXISTS "Admins can manage accounts" ON public.account_profiles;
DROP POLICY IF EXISTS "Admins can read accounts" ON public.account_profiles;
CREATE POLICY "Admins can read accounts"
ON public.account_profiles FOR SELECT
TO authenticated
USING (public.is_app_admin());

REVOKE INSERT, UPDATE, DELETE ON public.account_profiles FROM authenticated;
GRANT SELECT ON public.account_profiles TO authenticated;
