-- Corrige o mercado do Cartola, a gestao de ADMs e torna convidados permanentes.

-- O normalizador antigo tratava comandos do SQL Editor (auth.uid() nulo) como
-- alteracoes de usuarios comuns. Mantemos o bloqueio para usuarios autenticados
-- que nao sao ADMs, mas liberamos migrations e operacoes internas do banco.
CREATE OR REPLACE FUNCTION public.normalize_player_category()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'UPDATE'
    AND (
      NEW.member_category IS DISTINCT FROM OLD.member_category
      OR NEW.is_selectable IS DISTINCT FROM OLD.is_selectable
    )
    AND auth.uid() IS NOT NULL
    AND NOT public.is_app_admin()
  THEN
    RAISE EXCEPTION 'Somente administradores podem alterar categoria e elegibilidade.';
  END IF;

  IF NEW.member_category IN ('wag', 'supporter') THEN
    NEW.is_selectable := false;
    NEW.player_profile := NULL;
    NEW.is_goalkeeper := false;
  ELSE
    NEW.player_profile := COALESCE(NEW.player_profile, 'midfield');
    NEW.is_goalkeeper := COALESCE(NEW.is_goalkeeper, false);
    IF NEW.member_category IN ('player', 'guest') THEN
      NEW.is_selectable := true;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- Convidados nao sao mais arquivados automaticamente ao terminar uma rodada.
DROP TRIGGER IF EXISTS rounds_archive_guests ON public.rounds;
DROP FUNCTION IF EXISTS public.archive_guest_after_finished_round();

CREATE OR REPLACE FUNCTION public.keep_playable_member_state()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.member_category = 'guest' THEN
    NEW.is_selectable := true;
  ELSIF NEW.member_category IN ('wag', 'supporter') THEN
    NEW.is_selectable := false;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS players_keep_playable_member_state ON public.players;
CREATE TRIGGER players_keep_playable_member_state
BEFORE INSERT OR UPDATE OF member_category, is_selectable ON public.players
FOR EACH ROW EXECUTE FUNCTION public.keep_playable_member_state();

-- O gatilho legado exige auth.uid() de ADM até para comandos de migration.
-- Suspendemos apenas esse gatilho durante o backfill e o restauramos em seguida.
ALTER TABLE public.players DISABLE TRIGGER players_normalize_category;

UPDATE public.players
SET is_selectable = true
WHERE member_category = 'guest' AND is_selectable = false;

ALTER TABLE public.players ENABLE TRIGGER players_normalize_category;

-- Consulta administrativa independente das politicas de leitura aninhadas.
CREATE OR REPLACE FUNCTION public.list_manageable_accounts()
RETURNS TABLE (
  user_id UUID,
  role TEXT,
  created_at TIMESTAMPTZ,
  player_id UUID,
  player_name TEXT,
  player_nickname TEXT,
  player_avatar_url TEXT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_app_admin() THEN
    RAISE EXCEPTION 'Somente administradores podem consultar acessos.';
  END IF;

  RETURN QUERY
  SELECT
    profile.user_id,
    profile.role,
    profile.created_at,
    player.id,
    player.name,
    player.nickname,
    player.avatar_url
  FROM public.account_profiles profile
  LEFT JOIN public.players player ON player.id = profile.player_id
  ORDER BY
    CASE WHEN profile.role = 'admin' THEN 0 ELSE 1 END,
    lower(COALESCE(player.name, profile.user_id::TEXT));
END;
$$;

REVOKE ALL ON FUNCTION public.list_manageable_accounts() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.list_manageable_accounts() TO authenticated;

CREATE TABLE IF NOT EXISTS public.admin_role_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  previous_role TEXT NOT NULL CHECK (previous_role IN ('admin', 'player')),
  new_role TEXT NOT NULL CHECK (new_role IN ('admin', 'player')),
  changed_by_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_role_audit ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS admin_role_audit_admin_read ON public.admin_role_audit;
CREATE POLICY admin_role_audit_admin_read
ON public.admin_role_audit FOR SELECT TO authenticated
USING (public.is_app_admin());
GRANT SELECT ON public.admin_role_audit TO authenticated;

CREATE OR REPLACE FUNCTION public.manage_account_admin_role(
  p_target_user_id UUID,
  p_make_admin BOOLEAN
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_role TEXT;
  desired_role TEXT := CASE WHEN p_make_admin THEN 'admin' ELSE 'player' END;
  admin_count INTEGER;
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_app_admin() THEN
    RAISE EXCEPTION 'Somente administradores podem alterar acessos.';
  END IF;

  SELECT profile.role INTO current_role
  FROM public.account_profiles profile
  WHERE profile.user_id = p_target_user_id
  FOR UPDATE;

  IF current_role IS NULL THEN
    RAISE EXCEPTION 'Conta cadastrada nao encontrada.';
  END IF;
  IF current_role = desired_role THEN
    RETURN desired_role;
  END IF;

  IF NOT p_make_admin THEN
    IF p_target_user_id = auth.uid() THEN
      RAISE EXCEPTION 'Voce nao pode remover o proprio acesso de administrador.';
    END IF;
    SELECT count(*)::INTEGER INTO admin_count
    FROM public.account_profiles profile
    WHERE profile.role = 'admin';
    IF admin_count <= 1 THEN
      RAISE EXCEPTION 'O aplicativo precisa manter pelo menos um administrador.';
    END IF;
  END IF;

  UPDATE public.account_profiles
  SET role = desired_role, updated_at = now()
  WHERE account_profiles.user_id = p_target_user_id;

  INSERT INTO public.admin_role_audit (
    target_user_id, previous_role, new_role, changed_by_user_id
  ) VALUES (
    p_target_user_id, current_role, desired_role, auth.uid()
  );

  RETURN desired_role;
END;
$$;

REVOKE ALL ON FUNCTION public.manage_account_admin_role(UUID, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.manage_account_admin_role(UUID, BOOLEAN) TO authenticated;

-- Todo jogador ou convidado novo entra imediatamente nos mercados ativos.
CREATE OR REPLACE FUNCTION public.sync_player_to_fantasy_market()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.is_selectable = true AND NEW.member_category IN ('player', 'guest') THEN
    INSERT INTO public.fantasy_player_prices (
      fantasy_season_id, player_id, current_price
    )
    SELECT fantasy_season.id, NEW.id, fantasy_season.initial_player_price
    FROM public.fantasy_seasons fantasy_season
    JOIN public.seasons season_item ON season_item.id = fantasy_season.season_id
    WHERE season_item.status = 'active'
    ON CONFLICT (fantasy_season_id, player_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS players_sync_fantasy_market ON public.players;
CREATE TRIGGER players_sync_fantasy_market
AFTER INSERT OR UPDATE OF member_category, is_selectable ON public.players
FOR EACH ROW EXECUTE FUNCTION public.sync_player_to_fantasy_market();

INSERT INTO public.fantasy_player_prices (
  fantasy_season_id, player_id, current_price
)
SELECT fantasy_season.id, player.id, fantasy_season.initial_player_price
FROM public.fantasy_seasons fantasy_season
JOIN public.seasons season_item ON season_item.id = fantasy_season.season_id
CROSS JOIN public.players player
WHERE season_item.status = 'active'
  AND player.is_selectable = true
  AND player.member_category IN ('player', 'guest')
ON CONFLICT (fantasy_season_id, player_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.ensure_fantasy_round(p_round_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_round public.rounds%ROWTYPE;
  current_settings public.fantasy_settings%ROWTYPE;
  v_fantasy_season_id UUID;
  v_fantasy_round_id UUID;
BEGIN
  SELECT * INTO current_round
  FROM public.rounds round_item
  WHERE round_item.id = p_round_id;

  IF NOT FOUND OR current_round.round_type <> 'official' OR current_round.status = 'finished' THEN
    RETURN NULL;
  END IF;

  INSERT INTO public.fantasy_settings (league_id)
  VALUES (current_round.league_id)
  ON CONFLICT (league_id) DO NOTHING;

  SELECT * INTO current_settings
  FROM public.fantasy_settings settings_item
  WHERE settings_item.league_id = current_round.league_id;

  INSERT INTO public.fantasy_seasons (league_id, season_id, initial_budget, initial_player_price)
  VALUES (
    current_round.league_id, current_round.season_id,
    current_settings.initial_budget, current_settings.initial_player_price
  )
  ON CONFLICT (season_id) DO UPDATE SET league_id = EXCLUDED.league_id
  RETURNING id INTO v_fantasy_season_id;

  INSERT INTO public.fantasy_player_prices (fantasy_season_id, player_id, current_price)
  SELECT v_fantasy_season_id, player.id, current_settings.initial_player_price
  FROM public.players player
  WHERE player.is_selectable = true
    AND player.member_category IN ('player', 'guest')
  ON CONFLICT (fantasy_season_id, player_id) DO NOTHING;

  INSERT INTO public.fantasy_rounds (fantasy_season_id, round_id, settings_snapshot)
  VALUES (
    v_fantasy_season_id, current_round.id,
    to_jsonb(current_settings) - 'league_id' - 'updated_at'
  )
  ON CONFLICT (round_id) DO UPDATE SET round_id = EXCLUDED.round_id
  RETURNING id INTO v_fantasy_round_id;

  RETURN v_fantasy_round_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.save_fantasy_lineup(
  p_round_id UUID,
  p_player_ids UUID[],
  p_captain_player_id UUID DEFAULT NULL,
  p_top_scorer_player_id UUID DEFAULT NULL,
  p_top_assist_player_id UUID DEFAULT NULL,
  p_top_team_id UUID DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_user UUID := auth.uid();
  current_round public.rounds%ROWTYPE;
  target_fantasy_round public.fantasy_rounds%ROWTYPE;
  target_fantasy_season public.fantasy_seasons%ROWTYPE;
  target_account public.fantasy_accounts%ROWTYPE;
  saved_lineup_id UUID;
  unique_count INTEGER;
  valid_count INTEGER;
  lineup_cost NUMERIC(10,2);
BEGIN
  IF current_user IS NULL THEN RAISE EXCEPTION 'Entre na sua conta para escalar.'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_round_id::TEXT, 0));

  SELECT * INTO current_round
  FROM public.rounds round_item
  WHERE round_item.id = p_round_id
  FOR UPDATE;
  IF NOT FOUND OR current_round.round_type <> 'official' THEN
    RAISE EXCEPTION 'Rodada oficial nao encontrada.';
  END IF;

  PERFORM public.ensure_fantasy_round(p_round_id);
  SELECT * INTO target_fantasy_round
  FROM public.fantasy_rounds fantasy_round_item
  WHERE fantasy_round_item.round_id = p_round_id
  FOR UPDATE;
  IF NOT FOUND OR target_fantasy_round.market_status <> 'open'
    OR EXISTS (SELECT 1 FROM public.matches match_item WHERE match_item.round_id = p_round_id AND match_item.started_at IS NOT NULL) THEN
    RAISE EXCEPTION 'O mercado desta rodada esta fechado.';
  END IF;

  SELECT * INTO target_fantasy_season
  FROM public.fantasy_seasons fantasy_season_item
  WHERE fantasy_season_item.id = target_fantasy_round.fantasy_season_id;

  SELECT count(DISTINCT selected.id), count(*)
  INTO unique_count, valid_count
  FROM unnest(COALESCE(p_player_ids, ARRAY[]::UUID[])) AS selected(id);
  IF unique_count <> valid_count THEN RAISE EXCEPTION 'Um jogador nao pode aparecer duas vezes.'; END IF;
  IF unique_count > 5 THEN RAISE EXCEPTION 'A escalacao aceita no maximo 5 jogadores.'; END IF;

  SELECT count(*) INTO valid_count
  FROM public.players player
  WHERE player.id = ANY(COALESCE(p_player_ids, ARRAY[]::UUID[]))
    AND player.is_selectable = true
    AND player.member_category IN ('player', 'guest');
  IF valid_count <> unique_count THEN RAISE EXCEPTION 'A escalacao contem um jogador inelegivel.'; END IF;
  IF p_captain_player_id IS NOT NULL AND NOT (p_captain_player_id = ANY(COALESCE(p_player_ids, ARRAY[]::UUID[]))) THEN
    RAISE EXCEPTION 'O capitao precisa estar entre os escalados.';
  END IF;
  IF p_top_team_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.teams team_item WHERE team_item.id = p_top_team_id AND team_item.round_id = p_round_id
  ) THEN RAISE EXCEPTION 'O time escolhido nao pertence a esta rodada.'; END IF;
  IF p_top_scorer_player_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.players player WHERE player.id = p_top_scorer_player_id AND player.is_selectable = true AND player.member_category IN ('player', 'guest')
  ) THEN RAISE EXCEPTION 'Palpite de artilheiro invalido.'; END IF;
  IF p_top_assist_player_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.players player WHERE player.id = p_top_assist_player_id AND player.is_selectable = true AND player.member_category IN ('player', 'guest')
  ) THEN RAISE EXCEPTION 'Palpite de garcom invalido.'; END IF;

  INSERT INTO public.fantasy_accounts (fantasy_season_id, user_id, current_budget)
  VALUES (target_fantasy_round.fantasy_season_id, current_user, target_fantasy_season.initial_budget)
  ON CONFLICT (fantasy_season_id, user_id) DO NOTHING;

  SELECT * INTO target_account
  FROM public.fantasy_accounts account_item
  WHERE account_item.fantasy_season_id = target_fantasy_round.fantasy_season_id
    AND account_item.user_id = current_user
  FOR UPDATE;

  INSERT INTO public.fantasy_player_prices (fantasy_season_id, player_id, current_price)
  SELECT target_fantasy_round.fantasy_season_id, player.id, target_fantasy_season.initial_player_price
  FROM public.players player
  WHERE player.id = ANY(COALESCE(p_player_ids, ARRAY[]::UUID[]))
  ON CONFLICT (fantasy_season_id, player_id) DO NOTHING;

  SELECT COALESCE(sum(price.current_price), 0) INTO lineup_cost
  FROM public.fantasy_player_prices price
  WHERE price.fantasy_season_id = target_fantasy_round.fantasy_season_id
    AND price.player_id = ANY(COALESCE(p_player_ids, ARRAY[]::UUID[]));
  IF lineup_cost > target_account.current_budget THEN
    RAISE EXCEPTION 'A escalacao ultrapassa o patrimonio disponivel.';
  END IF;

  INSERT INTO public.fantasy_lineups (
    fantasy_round_id, user_id, status, captain_player_id, top_scorer_player_id,
    top_assist_player_id, top_team_id, budget_before, lineup_cost, cash_remaining, updated_at
  ) VALUES (
    target_fantasy_round.id, current_user, 'draft', p_captain_player_id, p_top_scorer_player_id,
    p_top_assist_player_id, p_top_team_id, target_account.current_budget, lineup_cost,
    target_account.current_budget - lineup_cost, now()
  ) ON CONFLICT (fantasy_round_id, user_id) DO UPDATE SET
    status = 'draft', captain_player_id = EXCLUDED.captain_player_id,
    top_scorer_player_id = EXCLUDED.top_scorer_player_id,
    top_assist_player_id = EXCLUDED.top_assist_player_id,
    top_team_id = EXCLUDED.top_team_id,
    budget_before = EXCLUDED.budget_before,
    lineup_cost = EXCLUDED.lineup_cost,
    cash_remaining = EXCLUDED.cash_remaining,
    updated_at = now()
  RETURNING id INTO saved_lineup_id;

  DELETE FROM public.fantasy_lineup_players item WHERE item.lineup_id = saved_lineup_id;
  INSERT INTO public.fantasy_lineup_players (lineup_id, player_id, price_locked)
  SELECT saved_lineup_id, selected.id, price.current_price
  FROM unnest(COALESCE(p_player_ids, ARRAY[]::UUID[])) selected(id)
  JOIN public.fantasy_player_prices price
    ON price.fantasy_season_id = target_fantasy_round.fantasy_season_id
    AND price.player_id = selected.id;

  INSERT INTO public.fantasy_audit_log (league_id, fantasy_round_id, user_id, action, payload)
  VALUES (
    target_fantasy_season.league_id, target_fantasy_round.id, current_user,
    'lineup_saved', jsonb_build_object('players', unique_count, 'cost', lineup_cost)
  );
  RETURN saved_lineup_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.lock_fantasy_market(p_round_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_fantasy_round public.fantasy_rounds%ROWTYPE;
  target_fantasy_season public.fantasy_seasons%ROWTYPE;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_round_id::TEXT, 0));
  SELECT * INTO target_fantasy_round
  FROM public.fantasy_rounds fantasy_round_item
  WHERE fantasy_round_item.round_id = p_round_id
  FOR UPDATE;
  IF NOT FOUND OR target_fantasy_round.market_status <> 'open' THEN RETURN true; END IF;

  SELECT * INTO target_fantasy_season
  FROM public.fantasy_seasons fantasy_season_item
  WHERE fantasy_season_item.id = target_fantasy_round.fantasy_season_id;

  UPDATE public.fantasy_lineups lineup SET
    status = CASE WHEN (
      SELECT count(*) FROM public.fantasy_lineup_players item WHERE item.lineup_id = lineup.id
    ) = 5 AND lineup.captain_player_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM public.fantasy_lineup_players item
      WHERE item.lineup_id = lineup.id AND item.player_id = lineup.captain_player_id
    ) AND (
      SELECT count(*)
      FROM public.fantasy_lineup_players item
      JOIN public.players player ON player.id = item.player_id
      WHERE item.lineup_id = lineup.id
        AND player.is_selectable = true
        AND player.member_category IN ('player', 'guest')
    ) = 5 THEN 'locked' ELSE 'missed' END,
    locked_at = now(), updated_at = now()
  WHERE lineup.fantasy_round_id = target_fantasy_round.id;

  UPDATE public.fantasy_rounds
  SET market_status = 'in_progress', locked_at = now()
  WHERE id = target_fantasy_round.id;

  INSERT INTO public.fantasy_audit_log (league_id, fantasy_round_id, user_id, action)
  VALUES (target_fantasy_season.league_id, target_fantasy_round.id, auth.uid(), 'market_locked');
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.ensure_fantasy_round(UUID), public.lock_fantasy_market(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.save_fantasy_lineup(UUID, UUID[], UUID, UUID, UUID, UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.save_fantasy_lineup(UUID, UUID[], UUID, UUID, UUID, UUID) TO authenticated;
